name: Build app

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2" # Adjust the Ruby version here

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --path "vendor/bundle"

      - name: Run Rubocop
        run: bundle exec rubocop

      - name: Run tests
        run: bundle exec rspec

        env:
          AWS_CONF_ACCESS_KEY_ID: ""
          AWS_CONF_SECRET_ACCESS_KEY: "+JvZqq+"
          AWS_CONF_REGION: "ap-southeast-1"
          AWS_CONF_BUCKET_OUPUT: "-cm"
          AWS_CONF_MEDIA_CONVERT_ROLE: "arn:aws:iam:::role/"
